name: CI with Coverage

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          lcov \
          python3-pip
        pip install coveralls gcovr

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config Debug

    - name: Run tests
      working-directory: ./build
      run: |
        ctest --output-on-failure
        # Генерация coverage данных
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info \
          '/usr/*' \
          '*/tests/*' \
          '*/third_party/*' \
          -o filtered.info
        # Генерация HTML отчета (опционально)
        genhtml filtered.info --output-directory coverage_report

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALS_REPO_TOKEN }}
      run: |
        coveralls --gcov-options '\-lp' -i ./build/filtered.info
